### ISSUE TITLE
Persian

### ISSUE THREAD

**Issue by mahdisalehian** [olikraus/U8glib_Arduino#14]
Hello Dear Oliver
thanks for your library
I wanna use persian font. how can i do that?
u8g.setFont(u8g_font_6x10);
u8g.drawStr(62,10,"سلام"); 

can i print سلام directly?

**Comment by olikraus** [comment]
No, u8glib does not support UTF-8. However the successor tool u8g2 has support for this.
Please use u8g2 instead. It is available as library from the Arduino IDE.

see also:
https://github.com/olikraus/u8g2/issues/39
and 
https://github.com/olikraus/u8g2/issues/42
which describs the Extended UTF8 draw function with limited kerning and left to right writing feature.
