### ISSUE TITLE
SSD1306 Contrast Fix, same as 1309

### ISSUE THREAD

**Issue by openSoftMan** [olikraus/U8glib_Arduino#6]
Greetings,

I added this to u8g_dev_ssd1306_128x64.c per your fix for the 1309 and u8g.setContrast() works now :

tested with these 2 inits:
U8GLIB_SSD1306_128X64 u8g(U8G_I2C_OPT_DEV_0|U8G_I2C_OPT_NO_ACK|U8G_I2C_OPT_FAST);
U8GLIB_SSD1306_128X64 u8g(U8G_I2C_OPT_NO_ACK);

case U8G_DEV_MSG_CONTRAST:
      u8g_SetChipSelect(u8g, dev, 1);
      u8g_SetAddress(u8g, dev, 0);          /\* instruction mode _/
      u8g_WriteByte(u8g, dev, 0x081);
      u8g_WriteByte(u8g, dev, (_(uint8_t _)arg) ); /_ 11 Jul 2015: fixed contrast calculation */
      u8g_SetChipSelect(u8g, dev, 0);  
      return 1;

Thanks!

**Comment by olikraus** [comment]
looks like that this is already implemented. Please not that this is only the arduino copy of the real github project, which is u8glib
